version: '3.8'
services:
  # DEVELOPMENT
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: sh ./install.sh && sh ./start_dev.sh
    env_file:
      - '.env'
    ports:
      - "5003:8080"
    volumes:
      - .:/app
    environment:
      DATABASE_NAME: ${DATABASE_NAME?Variable not set}
      BACKEND_API: ${BACKEND_API?Variable not set}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY?Variable not set}

  # PRODUCTION
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '.env'
    ports:
      - "5000:8080"
    # volumes:
    #   - .:/golang-mux-gorm-boilerplate
    environment:
      DATABASE_NAME: ${DATABASE_NAME?Variable not set}
      BACKEND_API: ${BACKEND_API?Variable not set}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY?Variable not set}

volumes:
  database_data:

networks:
    default:
        name: test